---
driver_plugin: digitalocean
driver_config:
  region: nyc3
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14-04-x64
- name: debian-7-0-x64
suites:
- name: default
  run_list:
  - recipe[digitalocean_dns]
  attributes:
